# generated by datamodel-codegen:
#   filename:  stats.json
#   timestamp: 2024-05-21T08:16:12+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    open: str
    high: str
    low: str
    last: str
    volume: str
    volume_30day: str
    rfq_volume_24hour: str
    rfq_volume_30day: str
